In [281]:
#idea behind kmeans: https://medium.com/analytics-vidhya/k-means-clustering-with-python-beginner-tutorial-45a44c34e7f 
#csv file: https://figshare.com/articles/dataset/Main_Dataset_for_Evolution_of_Popular_Music_USA_1960_2010_/1309953 
import pandas as pd
import numpy as np
import random
from sklearn.cluster import KMeans

In [282]:
a = pd.read_csv("EvolutionPopUSA_MainData.csv")
X = a.drop(labels=["artist_name","decade", "fiveyear", "track_name","quarter","first_entry", "era", "cluster"], axis=1)
Y = a['artist_name_clean']

In [283]:
X = X.drop(X.columns[1:32], axis=1)
X

       recording_id      PC14  harm_M.0.M  ...  timb_33  timb_34  timb_35
0                 1  0.078046         232  ...        3        2        0
1                 2  0.669725         137  ...       23        6       22
2                 3  0.586680           4  ...       14        7       63
3                 4  1.319288          10  ...        4        9       27
4                 5  1.868048          57  ...       12        3       16
...             ...       ...         ...  ...      ...      ...      ...
17089         17090 -2.292467          31  ...        8       19        3
17090         17091 -0.767396         148  ...        0       21        0
17091         17092  0.659499         202  ...       68       25        1
17092         17093  0.040006         255  ...        0       13        2
17093         17094 -0.426100         282  ...        3        7        2

[17094 rows x 230 columns]

In [284]:
a = a.drop(labels=["cluster"], axis=1)
a

       recording_id  ... timb_35
0                 1  ...       0
1                 2  ...      22
2                 3  ...      63
3                 4  ...      27
4                 5  ...      16
...             ...  ...     ...
17089         17090  ...       3
17090         17091  ...       0
17091         17092  ...       1
17092         17093  ...       2
17093         17094  ...       2

[17094 rows x 268 columns]

In [285]:
kmeans = KMeans(n_clusters = 700)
kmeans.fit(X)
clusters = kmeans.predict(X)
a["cluster"]=clusters

In [287]:

recomenderOn = True 
while(recomenderOn):
  print("Please input a song you like: ")
  song = input()
  if song in open('EvolutionPopUSA_MainData.csv').read():
    index = (a.loc[a["track_name"] == song].index) + 2
    index = index.tolist()

    cluster = (a.iloc[index]["cluster"])

    cluster1 = cluster


    cluster1 = (int(round(cluster1)))

    z = (a[a["cluster"]==cluster1])


    d = z["track_name"].sample(n=10, random_state=1)

    print([d])
    print("Would you like to try another song? Please type 1 for yes and 2 for no")
    recommender = input()
    if int(recommender) == 1:  
      continue
    elif int(recommender) == 2:
      print("Hope you listen to the songs. Have a nice day!")
      break
    
  else: 
    print("You have lame taste. Please try another song.")
    continue

Please input a song you like:
Hearts
[8882             Far From Yours
8918    Let's Get Crazy Tonight
8896       There'll Come A Time
8906        Where Love Has Gone
8950           The Game Of Love
8902            Break My Stride
8825               Use Somebody
8868               Girl Watcher
8925        I'm Telling You Now
8922               Stop To Love
Name: track_name, dtype: object]
Would you like to try another song? Please type 1 for yes and 2 for no
1
Please input a song you like:
Russian Roulette
[14269                                  On A Carousel
14137                          Your Boyfriend's Back
14072                               Little Miss Blue
14278                                    Good Lovin'
14273    When The Boy's Happy (The Girl's Happy Too)
14257                                Talk To Me Baby
14270                                  Chicken Fried
14079                              He Ain't No Angel
14043                              A Wonder Like You
14104                        Turn On Your Love Light
Name: track_name, dtype: object]
Would you like to try another song? Please type 1 for yes and 2 for no
2
Hope you listen to the songs. Have a nice day!